/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_divconq_gtm_M */

#ifndef _Included_com_divconq_gtm_M
#define _Included_com_divconq_gtm_M
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_divconq_gtm_M
 * Method:    set
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_set
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    kill
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_kill
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    increment
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_increment
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_divconq_gtm_M
 * Method:    merge
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_merge
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    data
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_data
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    next
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_next
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    previous
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_previous
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    query
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_query
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    lock
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_lock
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    unlock
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_unlock
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    tStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_tStart
  (JNIEnv *, jobject);

/*
 * Class:     com_divconq_gtm_M
 * Method:    tCommit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_tCommit
  (JNIEnv *, jobject);

/*
 * Class:     com_divconq_gtm_M
 * Method:    tRollback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_tRollback
  (JNIEnv *, jobject);

/*
 * Class:     com_divconq_gtm_M
 * Method:    func
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_M_func
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_divconq_gtm_M
 * Method:    proc
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_M_proc
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
