/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_divconq_gtm_JavaM */

#ifndef _Included_com_divconq_gtm_JavaM
#define _Included_com_divconq_gtm_JavaM
#ifdef __cplusplus
extern "C" {
#endif
#undef com_divconq_gtm_JavaM_ORDER_FORWARD
#define com_divconq_gtm_JavaM_ORDER_FORWARD 1L
#undef com_divconq_gtm_JavaM_ORDER_BACKWARD
#define com_divconq_gtm_JavaM_ORDER_BACKWARD -1L
/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMSET
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_JavaM_GTMSET__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMSET
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_JavaM_GTMSET___3Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMGET
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_JavaM_GTMGET
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMKILL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_JavaM_GTMKILL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMORDER
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_JavaM_GTMORDER
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMQUERY
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_JavaM_GTMQUERY
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMINCREMENT
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_divconq_gtm_JavaM_GTMINCREMENT
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMTSTART
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_JavaM_GTMTSTART
  (JNIEnv *, jobject);

/*
 * Class:     com_divconq_gtm_JavaM
 * Method:    GTMTCOMMIT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_divconq_gtm_JavaM_GTMTCOMMIT
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
